config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tweets do
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
    member do
      get 'searches'
    end
  end
  resources :users, only: [:index, :show] do
    collection do
      get 'likes'
    end
  end
  root to: 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: 'ジャンル' },
    { id: 2, name: '洋食' },
    { id: 3, name: '中華' },
    { id: 4, name: '和食' },
  ]
  include ActiveHash::Associations
  has_many :tweets

  end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :likes, dependent: :destroy

  with_options presence: true do
    validates :image
    validates :name
    validates :ingredient
    validates :make
    validates :genre_id, numericality: { other_than: 1 } 
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  def self.search(search)
    if search != ""
      Tweet.where(['name LIKE(?) OR ingredient LIKE(?)', "%#{search}%", "%#{search}%"])
    else
      Tweet.all
    end
  end
  
  def self.searches(id)
    if id != ""
      Tweet.where('genre_id LIKE(?)', "%#{id}%")
    else
      Tweet.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
        has_one_attached :avatar
        has_many :tweets
        has_many :likes, dependent: :destroy

        with_options presence: true do
          validates :name
          validates :encrypted_password
          validates :avatar
          validates :email
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_tweet

  def create
    @like = Like.create(user_id: current_user.id, tweet_id: params[:tweet_id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, tweet_id: params[:tweet_id])
    like.destroy
  end

  private
  def set_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show, :edit, :update]
  before_action :choose_tweet, only:[:show, :edit, :update, :destroy]

  def index
    @tweets = Tweet.includes(:user).order("created_at DESC")
  end
  
  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to action: :index
    else
      render :edit
    end
  end

  def destroy
    @tweet.destroy
    redirect_to root_path
  end

  def search
    @tweets = Tweet.search(params[:keyword])
  end

  def searches
    @tweets = Tweet.searches(params[:id])
  end


  private
  def tweet_params
    params.require(:tweet).permit(:image, :name, :ingredient, :make, :genre_id).merge(user_id: current_user.id)
  end

  def choose_tweet
    @tweet = Tweet.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.order("created_at DESC")
  end

  def likes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recettes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
<% if user_signed_in? %>

  <% unless tweet.like_user(current_user.id).blank? %>
    <%= link_to tweet_like_path(tweet_id: tweet.id, id: tweet.likes[0].id), method: :delete, remote: true do %>
      <div class="vertical_like">
      <%= image_tag asset_path "like.png" %>
      </div>
    <% end %>
  <% else %>
    <%= link_to tweet_likes_path(tweet), method: :post, remote: true do %>
      <div class="vertical_like">
        <%= image_tag asset_path "n_like.png" %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$('#likes_buttons<%= @tweet.id %>').html("<%= j(render partial: 'like', locals: {tweet: @tweet,like: @like}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons<%= @tweet.id %>').html("<%= j(render partial: 'like', locals: {tweet: @tweet, like: @like}) %>");

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header class="header">
      <div class="header__bar">
        <h1>
          <%= link_to "Recettes", root_path, method: :get %>
        </h1>
        <% if user_signed_in? %>
          <div class="header_right">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :post %>
            <%= link_to "新規投稿", new_tweet_path, class: :post %>
          </div>
        <%# // ログインしているときは上記を表示するようにしましょう %>
        <% else %>
          <div class="header_right">
            <%= link_to "ログイン", new_user_session_path, class: :post %>
            <%= link_to "新規登録", new_user_registration_path, class: :post %>
          </div>
        <%# // ログインしていないときは上記を表示するようにしましょう %>
        <% end %>
      </div>
    </header>

app/views/tweets/_tweet_new.html.erb
<div class="container_new">
  <h3>投稿する</h3>
  <%= form_with model: @tweet, local: true do |f| %>
    <%= f.file_field :image, style: "border: none",id:"message_image" %>
    <div id="image-list"></div>
    <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"genre-select"}) %>
    <%= f.text_area :name, placeholder: "料理名" %>
    <%= f.text_area :ingredient, placeholder: "食材", rows: "10" %>
    <%= f.text_area :make, placeholder: "作り方", rows: "10" %>
    <%= f.submit "投稿" %>
  <% end %>
</div>

app/views/tweets/_tweets.html.erb
<div class="tweet_content">
  <% if @tweets == []%>
    <div>
    <P>検索結果がありません。</P>
    </div>
  <% else %>
    <% tweets.each do |tweet| %>
      <div class="tweet">
        <div class="text">
          <%= tweet.name %>
        </div>
        <div class="image">
          <%= link_to image_tag(tweet.image) , tweet_path(tweet.id), method: :get %>
        </div>
        <div id="likes_buttons<%= tweet.id %>">
        <%= render partial: 'likes/like', locals: { tweet: tweet, like: @like} %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/tweets/edit.html.erb
<%= render "shared/header" %>

<%= render 'shared/error_messages', model: @tweet %>

<%= render partial: "tweet_new"%>

app/views/tweets/index.html.erb
<header class="index_header">
  <div class="index_header_top">
    <h1>
      Recettes
    </h1>
  </div>
  <%= form_with(url: search_tweets_path, local: true, method: :get) do |form| %>
      <%= form.text_field :keyword, placeholder: "検索"%>
      <%= form.submit "検索"%>
    <% end %>
  <div class="index_header__bar">
    <% if user_signed_in? %>
      <div class="index_header_botom">
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :post %>
        <%= link_to "新規投稿", new_tweet_path, class: :post %>
      </div>
    <%# // ログインしているときは上記を表示するようにしましょう %>
    <% else %>
      <div class="index_header_botom">
        <%= link_to "ログイン", new_user_session_path, class: :post %>
        <%= link_to "新規登録", new_user_registration_path, class: :post %>
      </div>
    <%# // ログインしていないときは上記を表示するようにしましょう %>
    <% end %>
  </div>
</header>
<div class="main_content">
  <div class="left_bar">
    <% if user_signed_in? %>
    <div class="index_user_name">
      <%=link_to image_tag(current_user.avatar), user_path(current_user.id), method: :get%>
      <%=link_to current_user.name, user_path(current_user.id), method: :get, class: 'user_name'%>
    </div>
    <% end %>
    <ul>
      <% if user_signed_in? %>
        <li><%= link_to "いいね一覧", likes_users_path %> <%= image_tag asset_path('note.png') %></li>
      <% end %>
      <li><%= link_to "シェフ一覧", users_path %> <%= image_tag asset_path('hat.png') %></li>
      <li><%= link_to "洋食一覧", searches_tweet_path(2) %> <%= image_tag asset_path('pan.png') %></li>
      <li><%= link_to "中華料理一覧", searches_tweet_path(3) %> <%= image_tag asset_path('中華包丁.png') %></li>
      <li><%= link_to "和食一覧",  searches_tweet_path(4) %> <%= image_tag asset_path('wasyoku.png') %></li>
      <li class="dummy"></li>
    </ul>
  </div>
  
    <%= render partial: 'tweets', locals: { tweets: @tweets} %>
  
</div>
<div class="low_content">
  <div>
    <h3>Recettes</h3>
    <p>プロの料理人のためのレシピアプリです。</p>
    <p>調理業界には様々な考えをもった料理人がいます</p>
    <p>しかし、ほとんどの料理人は本を出したり</p>
    <p>店を持つことはありません。</p>
    <p>そこでこのアプリを作成しました。</p>
  </div>
</div>

<div class="message">
  <div class='message_image'></div>
  <div class="messages">
  <h3>全ての料理人にチャンスを</h3>
  <p>店を持っていなくても</p>
  <p>本を出してていなくても</p>
  <p>腕の良い料理人が</p>
  <p>自分をアピールできる場所</p>
  <p>世の中の人に</p>
  <p>もっと多くの料理人を</p>
  <p>知って欲しい</p>
  <p>そんな思を込めました</p>
  </div>
</div>

app/views/tweets/new.html.erb
<%= render "shared/header" %>

<%= render 'shared/error_messages', model: @tweet %>

<%= render partial: "tweet_new"%>

app/views/tweets/search.html.erb
<%= render "shared/header" %>

<%= render partial: 'tweets', locals: { tweets: @tweets} %>

app/views/tweets/searches.html.erb
<%= render "shared/header" %>

<%= render partial: 'tweets', locals: { tweets: @tweets} %>

app/views/tweets/show.html.erb
<%= render "shared/header" %>

<div class=user_name>
  <%=link_to image_tag(@tweet.user.avatar), user_path(@tweet.user.id), method: :get %>
  <%=link_to @tweet.user.name, user_path(@tweet.user.id), method: :get %>
</div>

<div class="show_image">
  <%= image_tag @tweet.image %>
</div>

<% if @tweet.user.id == current_user.id%>
  <div class=show_user>
    <%= link_to "編集", edit_tweet_path(@tweet.id), method: :get, class: "show_btn" %>
    <%= link_to "削除", tweet_path, method: :delete, class:"show_btn" %>
  </div>
<% end %>

<table border="1" class="table">
  <tbody>
    <tr>
      <th>料理名</th>
      <th style = "text-align: left;"><%= @tweet.name%></th>
    </tr>
    <tr>
      <th>材料</th>
      <th style = "text-align: left;"><%= simple_format @tweet.ingredient%></th>
    </tr>
    <tr>
      <th>作り方</th>
      <th style = "text-align: left;"><%= simple_format @tweet.make%></th>
    </tr>
  </tbody>
</table>

app/views/users/index.html.erb
<%= render "shared/header" %>

<h1 style = "text-align: center;">シェフ一覧</h1>

<div class="tweet_content">
    <% @users.each do |user| %>
      <div class="tweet">
        <div class="text">
          <%= user.name %>
        </div>
        <div class="image">
          <%= link_to image_tag(user.avatar) , user_path(user.id), method: :get %>
        </div>
      </div>
    <% end %>
  </div>

app/views/users/likes.html.erb
<%= render "shared/header" %>

<div class=user_name>
  <%= image_tag current_user.avatar%>
  <%= current_user.name %>さんがいいねした投稿一覧 
</div>
<div class="tweet_content">
  <% current_user.likes.each do |tweets| %>
    <% if tweets == []%>
      <div>
      <P>いいねした投稿はありません。</P>
      </div>
    <% else %>
        <div class="tweet">
          <div class="text">
            <%= tweets.tweet.name %>
          </div>
          <div class="image">
            <%= link_to image_tag(tweets.tweet.image) , tweet_path(tweets.tweet.id), method: :get %>
          </div>
          <div id="likes_buttons<%= tweets.tweet.id %>">
          <%= render partial: 'likes/like', locals: { tweet: tweets.tweet, like: @like} %>
          </div>
        </div>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<%= render "shared/header" %>
<div class=user_name>
  <%= image_tag @user.avatar%>
  <%= @user.name %>さんの投稿一覧 
</div>
<% if current_user.id == @user.id%>
  <div class="edit_user">
  <%= link_to "編集する", edit_user_registration_path, method: :get %>
  </div>
<% end %>
  <%= render partial: 'tweets/tweets', locals: { tweets: @tweets} %>